# Copyright 2026 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
ieee1905_utils.py

Reusable constants for IEEE 1905.1 / EasyMesh frame validation.

Currently provides:
- IEEE 1905.1 control multicast address constant
- TLV type constants
- Message type constants
"""

# ---------------------------------------------------------
# Constants
# ---------------------------------------------------------

# TLV Types
TLV_TYPE_END_OF_MESSAGE = 0x00
TLV_TYPE_AL_MAC_ADDRESS = 0x01
TLV_TYPE_MAC_ADDRESS = 0x02
TLV_TYPE_LINK_METRIC_QUERY = 0x08
TLV_TYPE_TX_LINK_METRIC = 0x09
TLV_TYPE_RX_LINK_METRIC = 0x0A
TLV_TYPE_SEARCHED_ROLE = 0x0D
TLV_TYPE_AUTOCONFIG_FREQ_BAND = 0x0E
TLV_TYPE_SUPPORTED_ROLE = 0x0F
TLV_TYPE_SUPPORTED_FREQ_BAND = 0x10
TLV_TYPE_MULTI_AP_PROFILE = 0xB3
TLV_TYPE_DEVICE_INFORMATION = 0x03
TLV_TYPE_AP_OPERATIONAL_BSS = 0x83
TLV_TYPE_BSS_CONFIG_REPORT = 0xB7
TLV_TYPE_WSC = 0x11
TLV_TYPE_AP_RADIO_BASIC_CAPABILITIES = 0x85
TLV_TYPE_PROFILE_2_AP_CAPABILITY = 0xB4
TLV_TYPE_AP_RADIO_ADVANCED_CAPABILITIES = 0xBE
TLV_TYPE_AP_RADIO_IDENTIFIER = 0x82
TLV_TYPE_END_OF_TLV = 0x00
TLV_TYPE_AP_CAPABILITY = 0xA1
TLV_TYPE_ERROR_CODE = 0xA3
TLV_TYPE_CHANNEL_PREFERENCE = 0x8B
TLV_TYPE_RADIO_OPERATION_RESTRICTION = 0x8C
TLV_TYPE_TRANSMIT_POWER_LIMIT = 0x8D
TLV_TYPE_CHANNEL_SELECTION_RESPONSE = 0x8E
TLV_TYPE_CHANNEL_SCAN_REQUEST = 0xA6
TLV_TYPE_CHANNEL_SCAN_RESULT = 0xA7
TLV_TYPE_TIMESTAMP = 0xA8
TLV_TYPE_OPERATING_CHANNEL = 0x8F
TLV_TYPE_CLIENT_INFO = 0x90
TLV_TYPE_CLIENT_CAPABILITY_REPORT = 0x91
TLV_TYPE_AP_METRICS_QUERY = 0x93
TLV_TYPE_AP_METRICS = 0x94
TLV_TYPE_STA_MAC_ADDRESS_TYPE = 0x95
TLV_TYPE_ASSOCIATED_STA_LINK_METRICS = 0x96
TLV_TYPE_UNASSOCIATED_STA_LINK_METRICS_QUERY = 0x97
TLV_TYPE_UNASSOCIATED_STA_LINK_METRICS_RESPONSE = 0x98
TLV_TYPE_BEACON_METRICS_QUERY = 0x99
TLV_TYPE_BEACON_METRICS_RESPONSE = 0x9A
TLV_TYPE_STEERING_REQUEST = 0x9B
TLV_TYPE_STEERING_BTM_REPORT = 0x9C
TLV_TYPE_CLIENT_ASSOCIATION_CONTROL_REQUEST = 0x9D
TLV_TYPE_BACKHAUL_STEERING_REQUEST = 0x9E
TLV_TYPE_BACKHAUL_STEERING_RESPONSE = 0x9F
TLV_TYPE_HIGHER_LAYER_DATA = 0xA0
TLV_TYPE_ASSOCIATED_STA_EXTENDED_LINK_METRICS = 0xC8
TLV_TYPE_PROFILE_2_STEERING_REQUEST = 0xC3
TLV_TYPE_ASSOCIATED_STA_TRAFFIC_STATS = 0xA2
TLV_TYPE_ASSOCIATED_WIFI_6_STA_STATUS_REPORT = 0xB0
TLV_TYPE_RADIO_METRICS = 0xC6
TLV_TYPE_AP_EXTENDED_METRICS = 0xC7
TLV_TYPE_CAC_COMPLETION_REPORT = 0xAF
TLV_TYPE_CAC_STATUS_REPORT = 0xB1
TLV_TYPE_CHANNEL_SCAN_CAPABILITIES = 0xA5
TLV_TYPE_CAC_REQUEST = 0xAD
TLV_TYPE_CAC_TERMINATION = 0xAE
TLV_TYPE_DEVICE_INVENTORY = 0xD4
TLV_TYPE_METRIC_COLLECTION_INTERVAL = 0xC5
TLV_TYPE_CAC_CAPABILITIES = 0xB2
TLV_TYPE_1905_LAYER_SECURITY_CAPABILITY = 0xA9
TLV_TYPE_CLIENT_ASSOCIATION_EVENT = 0x92
TLV_TYPE_DEVICE_BRIDGING_CAPABILITY = 0x04
TLV_TYPE_NON_1905_NEIGHBOR_DEVICE_LIST = 0x06
TLV_TYPE_1905_NEIGHBOR_DEVICE_LIST = 0x07
TLV_TYPE_SUPPORTED_SERVICE = 0x80
TLV_TYPE_SEARCHED_SERVICE = 0x81
TLV_TYPE_ASSOCIATED_CLIENTS = 0x84
TLV_TYPE_AP_HT_CAPABILITIES = 0x86
TLV_TYPE_AP_VHT_CAPABILITIES = 0x87
TLV_TYPE_AP_HE_CAPABILITIES = 0x88
TLV_TYPE_AP_WIFI_6_CAPABILITIES = 0xAA
TLV_TYPE_DEFAULT_802_1Q_SETTINGS = 0xB5
TLV_TYPE_TRAFFIC_SEPARATION_POLICY = 0xB6
TLV_TYPE_BSSID = 0xB8
TLV_TYPE_SERVICE_PRIORITIZATION_RULE = 0xB9
TLV_TYPE_DSCP_MAPPING_TABLE = 0xBA
TLV_TYPE_BSS_CONFIGURATION_REPORT = 0xB7
TLV_TYPE_BSS_CONFIGURATION_REQUEST = 0xBB
TLV_TYPE_BSS_CONFIGURATION_RESPONSE = 0xBD
TLV_TYPE_PROFILE_2_ERROR_CODE = 0xBC
TLV_TYPE_ASSOCIATION_STATUS_NOTIFICATION = 0xBF
TLV_TYPE_SOURCE_INFO = 0xC0
TLV_TYPE_STATUS_CODE = 0xC9
TLV_TYPE_DPP_MESSAGE = 0xD1
TLV_TYPE_TUNNELED_MESSAGE_TYPE = 0xC1
TLV_TYPE_TUNNELED = 0xC2
TLV_TYPE_1905_ENCAP_DPP = 0xCD
TLV_TYPE_1905_ENCAP_EAPOL = 0xCE
TLV_TYPE_DPP_BOOTSTRAPPING_URI_NOTIFICATION = 0xCF
TLV_TYPE_DPP_CHIRP_VALUE = 0xD3
TLV_TYPE_AGENT_LIST = 0xD5
TLV_TYPE_ANTICIPATED_CHANNEL_PREFERENCE = 0xD6
TLV_TYPE_ANTICIPATED_CHANNEL_USAGE = 0xD7
TLV_TYPE_CONTROLLER_CAPABILITY = 0xDD
TLV_TYPE_AP_RADIO_VBSS_CAPABILITIES = 0xDE
TLV_TYPE_BACKHAUL_STA_RADIO_CAPABILITIES = 0xCB
TLV_TYPE_REASON_CODE = 0xCA
TLV_TYPE_AKM_SUITE_CAPABILITIES = 0xCC
TLV_TYPE_STEERING_POLICY = 0x89
TLV_TYPE_METRIC_REPORTING_POLICY = 0x8A
TLV_TYPE_CHANNEL_SCAN_REPORTING_POLICY = 0xA4
TLV_TYPE_UNSUCCESSFUL_ASSOCIATION_POLICY = 0xC4
TLV_TYPE_BACKHAUL_BSS_CONFIGURATION = 0xD0
TLV_TYPE_DPP_CCE_INDICATION = 0xD2
TLV_TYPE_QOS_MANAGEMENT_POLICY = 0xDB
TLV_TYPE_QOS_MANAGEMENT_DESCRIPTOR = 0xDC
TLV_TYPE_SPATIAL_REUSE_CONFIG_RESPONSE = 0xDA
TLV_TYPE_SPATIAL_REUSE_REQUEST = 0xD8
TLV_TYPE_SPATIAL_REUSE_REPORT = 0xD9
TLV_TYPE_WIFI_7_AGENT_CAPABILITIES = 0xDF
TLV_TYPE_AGENT_AP_MLD_CONFIGURATION = 0xE0
TLV_TYPE_BACKHAUL_STA_MLD_CONFIGURATION = 0xE1
TLV_TYPE_ASSOCIATED_STA_MLD_CONFIGURATION = 0xE2
TLV_TYPE_MLD_STRUCTURE = 0xE3
TLV_TYPE_AFFILIATED_STA_METRICS = 0xE4
TLV_TYPE_AFFILIATED_AP_METRICS = 0xE5
TLV_TYPE_TID_TO_LINK_MAPPING_POLICY = 0xE6
TLV_TYPE_EHT_OPERATIONS = 0xE7
TLV_TYPE_AVAILABLE_SPECTRUM_INQUIRY_REQUEST = 0xE8
TLV_TYPE_AVAILABLE_SPECTRUM_INQUIRY_RESPONSE = 0xE9
TLV_TYPE_RSN_DIAGNOSTIC_REPORT = 0xEA
TLV_TYPE_RSN_PARAMETERS_CONFIGURATION = 0xEB
TLV_TYPE_BSS_ADVANCED_CONFIGURATION = 0xEC
TLV_TYPE_SUPPORTED_CIPHER_SUITES = 0xED


#MSG Types
MSG_TYPE_TOPOLOGY_DISCOVERY = 0x0000
MSG_TYPE_TOPOLOGY_NOTIFICATION = 0x0001
MSG_TYPE_AP_AUTOCONFIG_SEARCH = 0x0007
MSG_TYPE_AP_AUTOCONFIGURATION_RESPONSE = 0x0008
MSG_TYPE_1905_ACK = 0x8000
MSG_TYPE_AP_CAPABILITY_QUERY = 0x8001
MSG_TYPE_AP_CAPABILITY_REPORT = 0x8002
MSG_TYPE_CHANNEL_PREFERENCE_QUERY = 0x8004
MSG_TYPE_CHANNEL_PREFERENCE_REPORT = 0x8005
MSG_TYPE_AP_AUTOCONFIGURATION_RENEW = 0x000A
MSG_TYPE_AP_TOPOLOGY_QUERY = 0x0002
MSG_TYPE_AP_TOPOLOGY_RESPONSE = 0x0003
MSG_TYPE_AP_AUTOCONFIGURATION_WSC = 0x0009
MSG_TYPE_POLICY_CONFIG_REQUEST = 0x8003
MSG_TYPE_CHANNEL_SELECTION_REQUEST = 0x8006
MSG_TYPE_CHANNEL_SELECTION_RESPONSE = 0x8007
MSG_TYPE_OPERATING_CHANNEL_REPORT = 0x8008
MSG_TYPE_LINK_METRIC_QUERY = 0x0005
MSG_TYPE_LINK_METRIC_RESPONSE = 0x0006
MSG_TYPE_CLIENT_CAPABILITY_QUERY = 0x8009
MSG_TYPE_CLIENT_CAPABILITY_REPORT = 0x800A
MSG_TYPE_AP_METRICS_QUERY = 0x800B
MSG_TYPE_AP_METRICS_RESPONSE = 0x800C
MSG_TYPE_ASSOCIATED_STA_LINK_METRICS_QUERY = 0x800D
MSG_TYPE_ASSOCIATED_STA_LINK_METRICS_RESPONSE = 0x800E
MSG_TYPE_UNASSOCIATED_STA_LINK_METRICS_QUERY = 0x800F
MSG_TYPE_UNASSOCIATED_STA_LINK_METRICS_RESPONSE = 0x8010
MSG_TYPE_BEACON_METRICS_QUERY = 0x8011
MSG_TYPE_BEACON_METRICS_RESPONSE = 0x8012
MSG_TYPE_COMBINED_INFRASTRUCTURE_METRICS = 0x8013
MSG_TYPE_CLIENT_STEERING_REQUEST = 0x8014
MSG_TYPE_CLIENT_STEERING_BTM_REPORT = 0x8015
MSG_TYPE_CLIENT_ASSOCIATION_CONTROL_REQUEST = 0x8016
MSG_TYPE_STEERING_COMPLETED = 0x8017
MSG_TYPE_HIGHER_LAYER_DATA = 0x8018
MSG_TYPE_BACKHAUL_STEERING_REQUEST = 0x8019
MSG_TYPE_BACKHAUL_STEERING_RESPONSE = 0x801A
MSG_TYPE_CHANNEL_SCAN_REQUEST = 0x801B
MSG_TYPE_CHANNEL_SCAN_REPORT = 0x801C
MSG_TYPE_DPP_CCE_INDICATION = 0x801D
MSG_TYPE_1905_REKEY_REQUEST = 0x801E
MSG_TYPE_1905_DECRYPTION_FAILURE = 0x801F
MSG_TYPE_CAC_REQUEST = 0x8020
MSG_TYPE_CAC_TERMINATION = 0x8021
MSG_TYPE_CLIENT_DISASSOCIATION_STATS = 0x8022
MSG_TYPE_SERVICE_PRIORITIZATION_REQUEST = 0x8023
MSG_TYPE_ERROR_RESPONSE = 0x8024
MSG_TYPE_ASSOCIATION_STATUS_NOTIFICATION = 0x8025
MSG_TYPE_TUNNELED = 0x8026
MSG_TYPE_BACKHAUL_STA_CAPABILITY_QUERY = 0x8027
MSG_TYPE_BACKHAUL_STA_CAPABILITY_REPORT = 0x8028
MSG_TYPE_PROXIED_ENCAP_DPP = 0x8029
MSG_TYPE_DIRECT_ENCAP_DPP = 0x802A
MSG_TYPE_RECONFIGURATION_TRIGGER = 0x802B
MSG_TYPE_BSS_CONFIGURATION_REQUEST = 0x802C
MSG_TYPE_BSS_CONFIGURATION_RESPONSE = 0x802D
MSG_TYPE_BSS_CONFIGURATION_RESULT = 0x802E
MSG_TYPE_CHIRP_NOTIFICATION = 0x802F
MSG_TYPE_1905_ENCAP_EAPOL = 0x8030
MSG_TYPE_DPP_BOOTSTRAPPING_URI_NOTIFICATION = 0x8031
MSG_TYPE_ANTICIPATED_CHANNEL_PREFERENCE = 0x8032
MSG_TYPE_FAILED_CONNECTION = 0x8033
MSG_TYPE_AGENT_LIST = 0x8035
MSG_TYPE_ANTICIPATED_CHANNEL_USAGE_REPORT = 0x8036
MSG_TYPE_QOS_MANAGEMENT_NOTIFICATION = 0x8037
MSG_TYPE_VIRTUAL_BSS_CAPABILITIES_REQUEST = 0x8038
MSG_TYPE_VIRTUAL_BSS_CAPABILITIES_RESPONSE = 0x8039
MSG_TYPE_VIRTUAL_BSS_REQUEST = 0x803A
MSG_TYPE_VIRTUAL_BSS_RESPONSE = 0x803B
MSG_TYPE_CLIENT_SECURITY_CONTEXT_REQUEST = 0x803C
MSG_TYPE_CLIENT_SECURITY_CONTEXT_RESPONSE = 0x803D
MSG_TYPE_TRIGGER_CHANNEL_SWITCH_ANNOUNCEMENT_REQUEST = 0x803E
MSG_TYPE_TRIGGER_CHANNEL_SWITCH_ANNOUNCEMENT_RESPONSE = 0x803F
MSG_TYPE_VIRTUAL_BSS_MOVE_PREPARATION_REQUEST = 0x8040
MSG_TYPE_VIRTUAL_BSS_MOVE_PREPARATION_RESPONSE = 0x8041
MSG_TYPE_VIRTUAL_BSS_MOVE_CANCEL_REQUEST = 0x8042
MSG_TYPE_EARLY_AP_CAPABILITY_REPORT = 0x8043
MSG_TYPE_AP_MLD_CONFIGURATION_REQUEST = 0x8044
MSG_TYPE_AP_MLD_CONFIGURATION_RESPONSE = 0x8045
MSG_TYPE_BSTA_MLD_CONFIGURATION_REQUEST = 0x8046
MSG_TYPE_BSTA_MLD_CONFIGURATION_RESPONSE = 0x8047
CMDU_BSTA_MLD_CONFIGURATION_RESPONSE = 0x8047
MSG_TYPE_VIRTUAL_BSS_MOVE_CANCEL_RESPONSE = 0x8048
MSG_TYPE_AVAILABLE_SPECTRUM_INQUIRY = 0x8049
MSG_TYPE_OPERATING_CHANNEL_CHANGE_NOTIFICATION = 0x804A
MSG_TYPE_OPERATING_CHANNEL_QUERY = 0x804B
MSG_TYPE_BSS_CONFIGURATION_EXTENDED_REQUEST = 0x804C
MSG_TYPE_BSS_CONFIGURATION_EXTENDED_REPORT = 0x804D